// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGv9Q_KhjXO7T1Ijd_Wub4s0DyOnRYrUM',
    appId: '1:441885288309:web:8ba86cb25c55b2ab65953c',
    messagingSenderId: '441885288309',
    projectId: 'utpinme-beta',
    authDomain: 'utpinme-beta.firebaseapp.com',
    storageBucket: 'utpinme-beta.appspot.com',
    measurementId: 'G-DFQM99WDDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQTZfl5zG_WBMorY_6rBX5a-E6MewRKB4',
    appId: '1:441885288309:android:bb67e9710c37abbf65953c',
    messagingSenderId: '441885288309',
    projectId: 'utpinme-beta',
    storageBucket: 'utpinme-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE_hqpvoVe9O3Fa6ftMh3XHVgSL-e_ef8',
    appId: '1:441885288309:ios:fd6db0cd56db749a65953c',
    messagingSenderId: '441885288309',
    projectId: 'utpinme-beta',
    storageBucket: 'utpinme-beta.appspot.com',
    iosClientId: '441885288309-lj8efmhhdu39cvgngmv65tuvccu5g5ur.apps.googleusercontent.com',
    iosBundleId: 'com.example.utpInMe',
  );
}
